# Default initial positions for nova5_robot's ros2_control fake system
         
initial_positions:
  # joint1: 0.0
  # joint2: 0.0
  # joint3: 0.0
  # joint4: 0.0
  # joint5: 0.0
  # joint6: 0.0

  joint1: 0.00694641
  joint2: 1.5070569
  joint3: -1.29177054
  joint4: 2.90021252
  joint5: 1.66705122
  joint6: -0.05661848